package io.datajek.ftpservice.server;

import io.datajek.ftpservice.autogenerated.*;
import io.datajek.ftpservice.utils.ServerConfiguration;
import io.grpc.stub.StreamObserver;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.File;
import java.nio.file.*;

public class FTPService extends FTPServiceGrpc.FTPServiceImplBase {
    private static final Logger logger = LogManager.getLogger(FTPService.class.getName());
    private final Path destinationDirPath;
    Path tmpPath;

    public FTPService(ServerConfiguration serverConfiguration) {
        destinationDirPath = new File(serverConfiguration.getDestinationDirectoryOnServer()).toPath();
        tmpPath = new File(serverConfiguration.getTempWritePath()).toPath();
    }

    //addFile service method implementation
    @Override
    public StreamObserver<AddFileRequest> addFile(final StreamObserver<Result> resultObserver) {
        StreamObserver<AddFileRequest> requestObserver= null;
        return requestObserver;
    }
    //deleteFile service method implementation
    @Override
    public void deleteFile(MetaData request, StreamObserver<Result> responseObserver) {
    }
}
