/*
 * Copyright 2023, DataJek.io
 * All Rights Reserved
 */

package io.datajek.ftpservice.client;

import com.google.common.annotations.VisibleForTesting;
import com.google.protobuf.ByteString;
import io.datajek.ftpservice.autogenerated.*;
import io.datajek.ftpservice.utils.ClientConstants;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.stub.StreamObserver;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.NoSuchAlgorithmException;

import static io.datajek.ftpservice.utils.ClientConstants.ROUND_ROBIN;
import static io.datajek.ftpservice.utils.ClientUtils.computeChecksum;
import static java.lang.Thread.sleep;

/**
 * This class exposes two methods add and delete that can be used by customers
 * to add or delete files in the server's destination directory.
 * Instantiating a single client and using it to execute multiple operations is
 * preferred and more than performant than instantiating a new client for every
 * operation. This client also encapsulates the logic to chunk larger files when
 * transferring them over to the server. By default the chunk size is set to 4KB.
 * Developers who choose to implement the gRCP client themselves will then need
 * to implement the chunking logic themselves.
 */
public class FTPServiceClient implements AutoCloseable {

    private FTPServiceGrpc.FTPServiceStub asyncStub;
    private ManagedChannel channel;
    private int chunkSizeInBytes;

    /**
     * Private constructor that takes in a builder object to instantiate a
     * client
     *
     * @param builder
     */
    private FTPServiceClient(FTPServiceClientBuilder builder) throws IOException {

        chunkSizeInBytes = builder.chunkSizeInBytes;
        String serviceName = builder.serverAddress;

        channel = ManagedChannelBuilder.forAddress(serviceName, builder.insecureModePort)
                .usePlaintext()
                .defaultLoadBalancingPolicy(ROUND_ROBIN)
                .overrideAuthority(builder.overrideAuthority)
                .build();

        asyncStub = FTPServiceGrpc.newStub(channel);
    }

    /**
     * Returns the gRPC async stub. This method is used only for unit tests.
     *
     * @return
     */
    @VisibleForTesting
    public FTPServiceGrpc.FTPServiceStub getAsyncStub() {
        return asyncStub;
    }

    /**
     * Closes the managed channel.
     */
    public void close() throws InterruptedException {
        if (channel != null) {
            channel.shutdown();
        }
    }

    /**
     * This method transfers a given source file to the server's destination directory
     * with name destFileName. A large file is transferred in chunks and checksums are
     * matched to vet for transmission errors. Note that the behavior of this method is
     * unknown if multiple threads or processes attempt to transfer a file in parallel
     * with the same destFileName.
     *
     * @param sourceFilePath
     * @param destFileName
     * @param resultStreamObserver
     * @throws NoSuchAlgorithmException
     */
    public void addFile(String sourceFilePath, String destFileName, StreamObserver<Result> resultStreamObserver) {

        // request observer
        StreamObserver<AddFileRequest> addFileRequestObserver = asyncStub.addFile(resultStreamObserver);
        Path path = Paths.get(sourceFilePath);

        // check if the input file exists
        if (!Files.exists(path)) {
            throw new RuntimeException("File " + path.toString() + " doesn't exist");
        }

        // build and send metadata first
        AddFileRequest metadata =
                AddFileRequest.newBuilder().setMetadata(MetaData.newBuilder().setName(destFileName).build()).build();
        addFileRequestObserver.onNext(metadata);

        // send the source file in chunks
        InputStream inputStream = null;
        try {
            inputStream = Files.newInputStream(path);
            byte[] bytes = new byte[chunkSizeInBytes];
            int size;
            while ((size = inputStream.read(bytes)) > 0) {
                byte[] hash = computeChecksum(bytes, size);
                AddFileRequest addFileChunkRequest = AddFileRequest.newBuilder()
                        .setFileChunk(FileChunk.newBuilder()
                                .setContent(ByteString.copyFrom(bytes, 0, size))
                                .setChecksum(ByteString.copyFrom(hash, 0, hash.length))
                                .build())
                        .build();
                addFileRequestObserver.onNext(addFileChunkRequest);
            }
            addFileRequestObserver.onCompleted();
        } catch (IOException ioe) {
            // TODO: log an error message
            addFileRequestObserver.onError(new Exception());
        } finally {
            // close the stream
            try {
                inputStream.close();
            } catch (IOException ioe) {
                // TODO: log and error
                addFileRequestObserver.onError(new Exception());
            }
        }
    }

    /**
     * This method deletes a given file in the server's destination directory if present. In
     * case the file doesn't exist the return status is set to FILE_NOT_PRESENT.
     * Directories are never deleted. Errors callbacks are invoked for either of these
     * scenarios. The return status is set to FAILED, when a file can't
     * be deleted, e.g. due to permissions error. A successful deletion results
     * in the status set to SUCCESS.
     *
     * @param filenameToDelete
     * @param resultStreamObserver
     */
    public void deleteFile(String filenameToDelete, StreamObserver<Result> resultStreamObserver) {
        MetaData metaData = MetaData.newBuilder().setName(filenameToDelete).build();
        asyncStub.deleteFile(metaData, resultStreamObserver);
    }

    public void readFile(String filenameToDelete, StreamObserver<ReadFileResult> resultStreamObserver) {
        //try  using a blocking stub here and see what happens
        MetaData request = MetaData.newBuilder()
                .setName(filenameToDelete)
                .build();
        asyncStub.readFile(request, resultStreamObserver);
    }

    public void getFileAttributes(String[] fileNames, StreamObserver<FileAttributesResult> resultStreamObserver) {
        StreamObserver<MetaData> requestObserver = asyncStub.getFileAttributes(resultStreamObserver);

        for(String fileName: fileNames) {
            System.out.println("Sending request to get attributes of "+ fileName.trim());
            MetaData request = MetaData.newBuilder()
                    .setName(fileName)
                    .build();
            requestObserver.onNext(request);
            try {
                sleep(250);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }
        requestObserver.onCompleted();
    }

    /**
     * Use the client builder for instantiating FTPServiceClient objects. All
     * values are set to default when no parameters are overridden.
     */
    public static class FTPServiceClientBuilder {

        // defaults
        private int chunkSizeInBytes = ClientConstants.DEFAULT_CHUNK_SIZE_IN_BYTES;
        private String serverAddress = ClientConstants.LOCALHOST;
        private int insecureModePort = ClientConstants.DEFAULT_INSECURE_PORT;
        private String overrideAuthority = ClientConstants.OVERRIDE_AUTHORITY;

        public FTPServiceClientBuilder() {

        }

        public FTPServiceClientBuilder setServerAddress(String serverAddress) {
            this.serverAddress = serverAddress;
            return this;
        }

        public FTPServiceClientBuilder setChunkSize(int chunkSizeInBytes) {
            this.chunkSizeInBytes = chunkSizeInBytes;
            return this;
        }

        public FTPServiceClientBuilder setInsecureModePort(int insecureModePort) {
            this.insecureModePort = insecureModePort;
            return this;
        }

        public FTPServiceClientBuilder setOverrideAuthority(String overrideAuthority) {
            this.overrideAuthority = overrideAuthority;
            return this;
        }

        public FTPServiceClient build() throws IOException {
            return new FTPServiceClient(this);
        }
    }
}